version: "3"
services:

  keycloak:
    image: openfact/keycloak-postgres
    environment:
      - POSTGRES_PORT_5432_TCP_ADDR=postgres
      - POSTGRES_PORT_5432_TCP_PORT=5432
    ports:
      - 8080:8080
    networks:
      - sso
    depends_on:
      - postgres
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  postgres:
    image: postgres:9.4
    environment:
      POSTGRES_ROOT_PASSWORD: root_password
      POSTGRES_DATABASE: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - sso
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  sso:

volumes:
  db-data: