keycloak_db:
  image: postgres
  environment:
    POSTGRES_ROOT_PASSWORD: root_password
    DB_DATABASE: keycloak
    DB_USERNAME: keycloak
    DB_PASSWORD: password
openfact_db:
  image: postgres
  environment:
      POSTGRES_ROOT_PASSWORD: root_password
      DB_DATABASE: openfact
      DB_USERNAME: openfact
      DB_PASSWORD: password
keycloak:
  image: openfact/keycloak-postgres
  links:
    - keycloak_db:postgres
  ports:
    - 8081:8080
openfact:
  image: openfact/openfact-postgres
  links:
    - openfact_db:postgres
    - keycloak:keycloak
  ports:
      - 8080:8080